workspace "FrogEngine2D"

	architecture "x64"
	
	configurations
	{
		"Debug",
		"Release",
		"Dist"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

project "FrogEngine2D"

	location "FrogEngine2D"

	kind "SharedLib" --dll

	language "C"

	targetdirectory ("bin/" .. outputdir .. "/%{prj.name}")
	objdirectory ("bin-int/" .. outputdir .. "/%{prj.name}")

	files
	{
		"%{prj.name}/src/**.h"
		"%{prj.name}/src/**.c"
	}

	include -- no includes yet
	{
		-- "%{prj.name}/vendor/xx/include"
	}

	filter "system:windows"
		-- C dialect cdialect "C bla"

		staticruntime "On" --linking runtime libraries statically

		systemversion "latest" -- windows sdk verion

		defines
		{
			"FE_PLATFORM_WINDOWS"
			"FE_BUILD_DLL"
			--"WINDLL" <- automatically generated by vs
		}

		postbuildcommands
		{
			-- copies FrogEngin2D dll into Sandbox exe folder
			("{COPY} %{cfg.buildtarget.relpath} ../bin/" .. outputdir .. "/Sandbox") 
		}

		filter "configurations:Debug"
			defines "FE_DEBUG"
			symbols "On"

		filter "configurations:Release"
			defines "FE_Releasy"
			optimize "On"

		filter "configurations:Dist"
			defines "FE_Dist"
			optimize "On"

		-- example of multiple filter
		--filter {"system:windows", "configuration:Release"}
		--	buildoptions "/MT" -- uses Multithreaded runtime library